'use client';

import { ArrowUpRight } from 'lucide-react';
import Link from 'next/link';
import * as React from 'react';

import { Container } from '@/components/Container';
import { merchantApi } from '@/lib/api/merchant';
import { useTranslation } from '@/lib/i18n';
import { orderStatuses, type MerchantOrder, type OrderStatus } from '@/lib/schemas/merchant';

export function MerchantOrders() {
  const { lang, t } = useTranslation(); const [items, setItems] = React.useState<MerchantOrder[]>([]); const [cursor, setCursor] = React.useState<string | null>(); const [status, setStatus] = React.useState<OrderStatus | ''>(''); const [busy, setBusy] = React.useState(true); const [error, setError] = React.useState('');
  const load = React.useCallback(async (next?: string, append = false) => { setBusy(true); setError(''); try { const page = await merchantApi.orders({ cursor: next, limit: 20, status: status || undefined }); setItems((old) => append ? [...old, ...page.items] : page.items); setCursor(page.nextCursor ?? null); } catch { setError(t('merchant.error_load')); } finally { setBusy(false); } }, [status, t]);
  React.useEffect(() => {
    const timer = window.setTimeout(() => void load(), 0);
    return () => window.clearTimeout(timer);
  }, [load]);
  return <Container className="py-8 sm:py-12"><header className="border-b border-border pb-7"><p className="text-[length:var(--text-overline)] font-bold uppercase text-primary">{t('merchant.workspace')}</p><h1 className="mt-2 text-[length:var(--text-h1)] font-bold">{t('merchant.orders')}</h1><p className="mt-2 text-muted-foreground">{t('merchant.orders_subtitle')}</p></header><label className="mt-6 block max-w-xs text-[length:var(--text-label)] font-semibold">{t('merchant.filter_status')}<select value={status} onChange={(event) => setStatus(event.target.value as OrderStatus | '')} className="mt-2 min-h-12 w-full rounded-md border border-input bg-background px-3"><option value="">{t('merchant.all_statuses')}</option>{orderStatuses.map((value) => <option key={value} value={value}>{t(`merchant.status_${value}`)}</option>)}</select></label>{error && <p role="alert" className="mt-5 bg-error/12 px-4 py-3 text-error">{error}</p>}<div className="mt-6 overflow-x-auto border-y border-border"><table className="w-full min-w-[760px]"><thead><tr className="text-[length:var(--text-label)] text-muted-foreground"><th className="px-3 py-4 text-start">{t('merchant.order')}</th><th className="px-3 py-4 text-start">{t('merchant.created')}</th><th className="px-3 py-4 text-start">{t('merchant.unit')}</th><th className="px-3 py-4 text-start">{t('merchant.total')}</th><th className="px-3 py-4 text-start">{t('merchant.status')}</th><th className="px-3 py-4" /></tr></thead><tbody>{items.map((order) => <tr key={order.id} className="border-t border-border"><td className="px-3 py-4 font-bold">#{order.id.slice(-6).toUpperCase()}</td><td className="px-3 py-4 text-muted-foreground">{new Intl.DateTimeFormat(lang === 'ar' ? 'ar-EG' : 'en-GB', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(order.createdAt))}</td><td className="px-3 py-4">{order.deliveryUnit}</td><td className="px-3 py-4 font-semibold">{new Intl.NumberFormat(lang === 'ar' ? 'ar-EG' : 'en-EG', { style: 'currency', currency: 'EGP' }).format(order.totalAmount)}</td><td className="px-3 py-4"><Status status={order.status} /></td><td className="px-3 py-4 text-end"><Link href={`/merchant/orders/${order.id}`} aria-label={`${t('merchant.view_order')} ${order.id}`} className="inline-grid size-11 place-items-center rounded-md hover:bg-muted focus-visible:outline-2 focus-visible:outline-gold-500"><ArrowUpRight className="size-5 rtl:-scale-x-100" /></Link></td></tr>)}</tbody></table></div>{!busy && items.length === 0 && <p className="py-12 text-center text-muted-foreground">{t('merchant.empty_orders')}</p>}{busy && <p role="status" className="py-6 text-muted-foreground">{t('common.loading')}</p>}{cursor && !busy && <button type="button" onClick={() => void load(cursor, true)} className="mt-6 min-h-12 rounded-md border border-border px-5 font-bold hover:bg-muted">{t('merchant.load_more')}</button>}</Container>;
}

export function Status({ status }: { status: OrderStatus }) { const { t } = useTranslation(); const color = status === 'CANCELLED' ? 'text-error border-error/40' : status === 'DELIVERED' || status === 'READY' ? 'text-success border-success/40' : status === 'PREPARING' ? 'text-warning border-warning/40' : 'text-info border-info/40'; return <span className={`inline-flex min-h-8 items-center rounded-full border px-3 text-[length:var(--text-caption)] font-bold ${color}`}>{t(`merchant.status_${status}`)}</span>; }
